# The language in this case has no bearing - we are going to be making use of conda for a
# python distribution for the scientific python stack.
language: generic

sudo: false

env:
    global:
       - CONDA_INSTALL_LOCN="${HOME}/conda"

       # Adds a GH_TOKEN (conda-forge-coordinator's conda-forge.github.io token)
       - secure: "BshSms+7ZjWWtQNNzszt3ho76oWOTPeoNg+Aahmq1ZXJsAvh93IyHIxtb2xHYMrRdWXtCXof8kC1BLAjRISzL8j4+/QN6B8sjjrRYSBuM8WoCbP6c3DFbWJ2s19s5gAToqghahEP4VBJJcSny+gIzfNdKg47frwrcKLbvpzqr1q8O7H1swTXmXisplj9g5U7SWzP3lxveYxxcuh+/RTwQpQp8RriviCnacgZ6xJ3TnIirnhyyVOnA0twk3+0pSjpMSAsQY4+tTEDtIbHHUwEZxXS6sVNd/oVKBXNNHY/TJJRq413WvE7IGqyDtPQ935OAxHqiZFnA8WFQs9xK7EKssMsxXzRSOEPPCtDBMfL/4kDHF5gkF28NH9JJ9fgXxOpMm8SvFETe0nwUxSeb8uLPiw4UbXoKrd0Phxn/YyN3DOvRYKwsQpKYCGrzy+XNHmkoC80pI1OrqogtsUlUbRH0aS/6Zf7wn5ig3rVvMvhwYM/KbFPlb1z2tjb34GcFSpOsomXWvpLpG5gO91hFq9XPw0btsDq0aTJuJiAGrLKoMtkcY1FPe+M8wac2iRkfBCmbqr6HuCNdx7MCkPNysyfc+emeJIuxwhgcE1qLbTZMJ4ctMr2a2NGuoCxyWXOcNSVtUtlk5Q0rhgD0vohk/tKDdxJve9gw5qjihBjTsloTPg="

    matrix:
        - ACTION="feedstocks_repo"
        - ACTION="update_docs"

install:
    - mkdir -p ${HOME}/cache/pkgs
    - "[ ! -f ${HOME}/cache/miniconda.sh ] && wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/cache/miniconda.sh || :"
    - bash ${HOME}/cache/miniconda.sh -b -p ${CONDA_INSTALL_LOCN} && export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH

    # Re-use the packages in the cache, and download any new ones into that location.
    - rm -rf ${CONDA_INSTALL_LOCN}/pkgs && ln -s ${HOME}/cache/pkgs ${CONDA_INSTALL_LOCN}/pkgs

    - git config --global user.name "Travis-CI on github.com/conda-forge/conda-forge.github.io"
    - git config --global user.email conda.forge.coordinator@gmail.com
    - mkdir -p ~/.conda-smithy && echo $GH_TOKEN > ~/.conda-smithy/github.token

    # Now do the things we need to do to install it.
    - conda install conda-execute --yes --quiet -c conda-forge

script:
    - if [ $ACTION = "update_docs" ]; then
        echo "Updating docs";
        source ./.ci_scripts/update_docs;
      elif [ "$ACTION" = "feedstocks_repo" ]; then
        echo "Updating feedstock repo";
        source ./.ci_scripts/update_feedstocks_repo;
      fi

# We store the files that are downloaded from continuum.io, but not the environments that are created.
cache:
    directories:
      - $HOME/cache
before_cache:
  # Remove all untarred directories.
  - find $CONDA_INSTALL_LOCN/pkgs/ -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
