[workspace]
authors = ["conda-forge/core <conda-forge-core@googlegroups.com>"]
channels = ["conda-forge"]
name = "conda-forge.github.io"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
start = { cmd = "npm run start", description = "Live-reload deployment for local development." }
build-production = { cmd = "bash ./.ci_scripts/update_docs", description = "Build site for production." }

[dependencies]
curl = "*"
nodejs = "24.*"
pre-commit = "*"
python = "3.*"
requests = "*"

[target.win-64.dependencies]
m2-bash = "*"
