[workspace]
authors = ["conda-forge/core <conda-forge-core@googlegroups.com>"]
channels = ["conda-forge"]
name = "conda-forge.github.io"
platforms = ["linux-64", "osx-arm64", "win-64"]

[tasks]
install = { cmd = "npm install", description = "Install Node packages."}
start = { cmd = "npm run start", description = "Live-reload deployment for local development.", depends-on = ["install"]}
build-production = { cmd = "bash ./.ci_scripts/update_docs", description = "Build site for production." }
lint = { cmd = "pre-commit run --all-files", description = "Run pre-commit hooks to lint the codebase." }

[dependencies]
curl = "*"
nodejs = "24.*"
pre-commit = "*"
python = "3.*"
requests = "*"

[target.win-64.dependencies]
m2-bash = "*"
