name: conda-forge-docs
channels:
  - conda-forge
dependencies:
  - python=3
  - conda-smithy
  - sphinx >=4.4
  - cloud_sptheme
  - sphinxcontrib-fulltoc
  - make
  - xonsh
  - myst-parser
  - pyyaml
  - jinja2
  - requests
  - python-dateutil
  - pip
  - python-rapidjson
  - termcolor
  - nodejs 20.*
  - ruamel.yaml
  - pip:
    - https://github.com/jaimergp/sphinx-markdown-builder/archive/admonitions.tar.gz
